### ISSUE TITLE
might be able to simplify a bit

### ISSUE THREAD

**Issue by bionicles** [ocrickard/fhir-rs#3]
interesting library!

in looking at models/Account.rs, I noticed this pattern repeated a lot

```
        if let Some(val) = self.value.get("_description") {
            return Some(Element {
                value: Cow::Borrowed(val),
            });
        }
        return None;
```

is it possible you think to make a Prism for that? 

it'a a way to define a getter/setter pair for an object, or none, if it doesn't exist. 

I literally don't know rust yet but it might be something like this:
```
let description_prism: ResourcePrism = ResourcePrism::from_str("_description")
let maybe_description: Option<Element> = view(description_prism, account)
```

not sure if there's a great rust crate for functional programming optics but even if you rolled it yourself it would allow you to delete a lot of code!

plus you could immutably update the resources with the same strategy

```rs
let account_with_new_description: Account = over(description_prism, always("my new description!"), account)
```

**Comment by bionicles** [comment]
heck, you could make an abstract resource, and it's got any resource json in it, and it can just look up the validator for the resource type written in the json. then you could write 1 struct instead of 145, and a bunch of prisms, and the whole thing might fit in one file

**Comment by ocrickard** [comment]
Love these ideas. I don't do much Rust. Let me add my generation script to the repo so that people can propose changes to it.

**Comment by ocrickard** [comment]
Here's the repo for the generation script, it's not pretty, but it works. Whatever we implemented here would have to be added to the codegen script in order to future-proof it for new schema changes.

https://github.com/ocrickard/fhir-rs-parser
